from enum import Enum

class AccuracyFulfilmentIndicator(str, Enum):
    REQUESTED_ACCURACY_FULFILLED = "REQUESTED_ACCURACY_FULFILLED"
    REQUESTED_ACCURACY_NOT_FULFILLED = "REQUESTED_ACCURACY_NOT_FULFILLED"