from enum import Enum

class LdrType(str, Enum):
    UE_AVAILABLE = "UE_AVAILABLE"
    PERIODIC = "PERIODIC"
    ENTERING_INTO_AREA = "ENTERING_INTO_AREA"
    LEAVING_FROM_AREA = "LEAVING_FROM_AREA"
    BEING_INSIDE_AREA = "BEING_INSIDE_AREA"
    MOTION = "MOTION"