from enum import Enum

class LocationFailureCause(str, Enum):
    POSITIONING_DENIED = "POSITIONING_DENIED"
    UNSUPPORTED_BY_UE = "UNSUPPORTED_BY_UE"
    NOT_REGISTERED_UE = "NOT_REGISTERED_UE"
    UNSPECIFIED = "UNSPECIFIED"
    REQUESTED_AREA_NOT_ALLOWED = "REQUESTED_AREA_NOT_ALLOWED"