from enum import Enum

class LocationType(str, Enum):
    CURRENT_LOCATION = "CURRENT_LOCATION"
    LAST_KNOWN_LOCATION = "LAST_KNOWN_LOCATION"
    CURRENT_OR_LAST_KNOWN_LOCATION = "CURRENT_OR_LAST_KNOWN_LOCATION"
    INITIAL_LOCATION = "INITIAL_LOCATION"