import datetime
from enum import Enum
from typing import Annotated, List, Optional
from pydantic import BaseModel, Field, StrictBool, StrictStr, field_validator, validator
from models.MonitoringType import MonitoringType
from models.assication_type import AssociationType
from models.ddd_traffic_descriptor import DddTrafficDescriptor
from models.dl_data_delivery_status import DlDataDeliveryStatus
from models.ip_addr import IpAddr
from models.ldr_type import LdrType
from models.location_area import LocationArea
from models.location_area5_g import LocationArea5G
from models.location_qo_s import LocationQoS
from models.location_type import LocationType
from models.monitoring_event_report import MonitoringEventReport
from models.ranging_sl_result import RangingSlResult
from models.reachability_type import ReachabilityType
from datetime import datetime

from models.related_ue import RelatedUE
from models.sac_info import SACInfo
from models.sac_rep_format import SACRepFormat
from models.snssai import Snssai
from models.sub_type import SubType
from models.supported_gad_shapes import SupportedGADShapes
from models.time_window import TimeWindow
from models.uav_policy import UavPolicy
from models.up_loc_rep_addr_af_rm import UpLocRepAddrAfRm
from models.velocity_requested import VelocityRequested
from models.websock_notif_config import WebsockNotifConfig

class Accuracy(str, Enum):
    CGI_ECGI = "CGI_ECGI"
    ENODEB = "ENODEB"
    TA_RA = "TA_RA"
    PLMN = "PLMN"
    TWAN_ID = "TWAN_ID"
    GEO_AREA = "GEO_AREA"
    CIVIC_ADDR = "CIVIC_ADDR"

    
class MonitoringEventSubscription(BaseModel):
    msisdn: str = Field(default="")
    ExternalId: str = Field(default="")
    notificationDestination: str
    monitoringType: MonitoringType
    maximum_number_of_reports: Optional[Annotated[int, Field(strict=True, ge=1)]] = Field(default=None, description="Identifies the maximum number of event reports to be generated by the HSS, MME/SGSN as specified in clause 5.6.0 of 3GPP TS 23.682. ", alias="maximumNumberOfReports")
    rep_period: Optional[Annotated[int, Field(strict=True, ge=0)]] = Field(default=None, description="Unsigned integer identifying a period of time in units of seconds.", alias="repPeriod")
    group_report_guard_time: Optional[Annotated[int, Field(strict=True, ge=0)]] = Field(default=None, description="Unsigned integer identifying a period of time in units of seconds.", alias="groupReportGuardTime")
    maximum_detection_time: Optional[Annotated[int, Field(strict=True, ge=0)]] = Field(default=None, description="Unsigned integer identifying a period of time in units of seconds.", alias="maximumDetectionTime")
    var_self: Optional[StrictStr] = Field(default=None, description="string formatted according to IETF RFC 3986 identifying a referenced resource.", alias="self")
    supported_features: Optional[Annotated[str, Field(strict=True)]] = Field(default=None, description="A string used to indicate the features supported by an API that is used as defined in clause  6.6 in 3GPP TS 29.500. The string shall contain a bitmask indicating supported features in  hexadecimal representation Each character in the string shall take a value of \"0\" to \"9\",  \"a\" to \"f\" or \"A\" to \"F\" and shall represent the support of 4 features as described in  table 5.2.2-3. The most significant character representing the highest-numbered features shall  appear first in the string, and the character representing features 1 to 4 shall appear last  in the string. The list of features and their numbering (starting with 1) are defined  separately for each API. If the string contains a lower number of characters than there are  defined features for an API, all features that would be represented by characters that are not  present in the string are not supported. ", alias="supportedFeatures")
    mtc_provider_id: Optional[StrictStr] = Field(default=None, description="Identifies the MTC Service Provider and/or MTC Application.", alias="mtcProviderId")
    app_ids: Optional[Annotated[List[StrictStr], Field(min_length=1)]] = Field(default=None, description="Identifies the Application Identifier(s)", alias="appIds")
    added_external_ids: Optional[Annotated[List[StrictStr], Field(min_length=1)]] = Field(default=None, description="Indicates the added external Identifier(s) within the active group.", alias="addedExternalIds")
    added_msisdns: Optional[Annotated[List[StrictStr], Field(min_length=1)]] = Field(default=None, description="Indicates the added MSISDN(s) within the active group.", alias="addedMsisdns")
    excluded_external_ids: Optional[Annotated[List[StrictStr], Field(min_length=1)]] = Field(default=None, description="Indicates cancellation of the external Identifier(s) within the active group.", alias="excludedExternalIds")
    excluded_msisdns: Optional[Annotated[List[StrictStr], Field(min_length=1)]] = Field(default=None, description="Indicates cancellation of the MSISDN(s) within the active group.", alias="excludedMsisdns")
    external_group_id: Optional[StrictStr] = Field(default=None, description="string containing a local identifier followed by \"@\" and a domain identifier. Both the local identifier and the domain identifier shall be encoded as strings that do not contain any \"@\" characters. See Clauses 4.6.2 and 4.6.3 of 3GPP TS 23.682 for more information. ", alias="externalGroupId")
    add_ext_group_id: Optional[Annotated[List[StrictStr], Field(min_length=2)]] = Field(default=None, alias="addExtGroupId")
    ipv4_addr: Optional[StrictStr] = Field(default=None, description="string identifying a Ipv4 address formatted in the \"dotted decimal\" notation as defined in IETF RFC 1166. ", alias="ipv4Addr")
    ipv6_addr: Optional[StrictStr] = Field(default=None, description="string identifying a Ipv6 address formatted according to clause 4 in IETF RFC 5952. The mixed Ipv4 Ipv6 notation according to clause 5 of IETF RFC 5952 shall not be used. ", alias="ipv6Addr")
    dnn: Optional[StrictStr] = Field(default="")
    notification_destination: StrictStr = Field(description="string formatted according to IETF RFC 3986 identifying a referenced resource.", alias="notificationDestination")
    request_test_notification: Optional[StrictBool] = Field(default=None, description="Set to true by the SCS/AS to request the SCEF to send a test notification as defined in clause 5.2.5.3. Set to false by the SCS/AS indicates not request SCEF to send a test notification, default false if omitted otherwise. ", alias="requestTestNotification")
    monitor_expire_time: Optional[datetime] = Field(default=None, description="string with format \"date-time\" as defined in OpenAPI.", alias="monitorExpireTime")
    rep_period: Optional[Annotated[int, Field(strict=True, ge=0)]] = Field(default=None, description="Unsigned integer identifying a period of time in units of seconds.", alias="repPeriod")
    group_report_guard_time: Optional[Annotated[int, Field(strict=True, ge=0)]] = Field(default=None, description="Unsigned integer identifying a period of time in units of seconds.", alias="groupReportGuardTime")
    maximum_detection_time: Optional[Annotated[int, Field(strict=True, ge=0)]] = Field(default=None, description="Unsigned integer identifying a period of time in units of seconds.", alias="maximumDetectionTime")
    maximum_latency: Optional[Annotated[int, Field(strict=True, ge=0)]] = Field(default=None, description="Unsigned integer identifying a period of time in units of seconds.", alias="maximumLatency")
    maximum_response_time: Optional[Annotated[int, Field(strict=True, ge=0)]] = Field(default=None, description="Unsigned integer identifying a period of time in units of seconds.", alias="maximumResponseTime")
    suggested_number_of_dl_packets: Optional[Annotated[int, Field(strict=True, ge=0)]] = Field(default=None, description="If \"monitoringType\" is \"UE_REACHABILITY\", this parameter may be included to identify the number of packets that the serving gateway shall buffer in case that the UE is not reachable. ", alias="suggestedNumberOfDlPackets")
    idle_status_indication: Optional[StrictBool] = Field(default=None, description="If \"monitoringType\" is set to \"UE_REACHABILITY\" or \"AVAILABILITY_AFTER_DDN_FAILURE\", this parameter may be included to indicate the notification of when a UE, for which PSM is enabled, transitions into idle mode. \"true\"  indicates enabling of notification; \"false\"  indicate no need to notify. Default value is \"false\" if omitted. ", alias="idleStatusIndication")
    minimum_report_interval: Optional[Annotated[int, Field(strict=True, ge=0)]] = Field(default=None, description="Unsigned integer identifying a period of time in units of seconds.", alias="minimumReportInterval")
    max_rpt_expire_intvl: Optional[Annotated[int, Field(strict=True, ge=0)]] = Field(default=None, description="Unsigned integer identifying a period of time in units of seconds.", alias="maxRptExpireIntvl")
    sampling_interval: Optional[Annotated[int, Field(strict=True, ge=0)]] = Field(default=None, description="Unsigned integer identifying a period of time in units of seconds.", alias="samplingInterval")
    reporting_loc_est_ind: Optional[StrictBool] = Field(default=None, description="Indicates whether to request the location estimate for event reporting. If \"monitoringType\" is \"LOCATION_REPORTING\", this parameter may be included to indicate whether event reporting requires the location information. If set to true, the location estimation information shall be included in event reporting. If set to \"false\", indicates the location estimation information shall not be included in event reporting. Default \"false\" if omitted. ", alias="reportingLocEstInd")
    code_word: Optional[StrictStr] = Field(default=None, description="Contains the codeword", alias="codeWord")
    up_loc_rep_ind_af: Optional[StrictBool] = Field(default=False, description="Indicates whether location reporting over user plane is requested or not. \"true\" indicates the location reporting over user plane is requested. \"false\" indicates the location reporting over user plane is not requested. Default value is \"false\" if omitted. ", alias="upLocRepIndAf")
    linear_distance: Optional[Annotated[int, Field(le=10000, strict=True, ge=1)]] = Field(default=None, description="Minimum straight line distance moved by a UE to trigger a motion event report.", alias="linearDistance")
    svc_id: Optional[StrictStr] = Field(default=None, description="Contains the service identity", alias="svcId")
    max_age_of_loc_est: Optional[Annotated[int, Field(le=32767, strict=True, ge=0)]] = Field(default=None, description="Indicates value of the age of the location estimate.", alias="maxAgeOfLocEst")
    plmn_indication: Optional[StrictBool] = Field(default=None, description="If \"monitoringType\" is \"ROAMING_STATUS\", this parameter may be included to indicate the notification of UE's Serving PLMN ID. Value \"true\" indicates enabling of notification; \"false\" indicates disabling of notification. Default value is \"false\" if omitted. ", alias="plmnIndication")
    api_names: Optional[Annotated[List[StrictStr], Field(min_length=1)]] = Field(default=None, alias="apiNames")
    af_service_id: Optional[StrictStr] = Field(default=None, alias="afServiceId")
    immediate_rep: Optional[StrictBool] = Field(default=None, description="Indicates whether an immediate reporting is requested or not. \"true\" indicate an immediate reporting is requested. \"false\" indicate an immediate reporting is not requested. Default value \"false\" if omitted. ", alias="immediateRep")
    ses_est_ind: Optional[StrictBool] = Field(default=None, description="Set to true by the SCS/AS so that only UAV's with \"PDU session established for DNN(s) subject to aerial service\" are to be listed in the Event report. Set to false or default false if omitted otherwise. ", alias="sesEstInd")
    addn_mon_types: Optional[List[MonitoringType]] = Field(default=None, alias="addnMonTypes")
    ue_mac_addr: Optional[Annotated[str, Field(strict=True)]] = Field(default=None, description="String identifying a MAC address formatted in the hexadecimal notation according to clause 1.1 and clause 2.1 of RFC 7042. ", alias="ueMacAddr")
    revocation_notif_uri: Optional[StrictStr] = Field(default=None, description="string providing an URI formatted according to IETF RFC 3986.", alias="revocationNotifUri")
    websock_notif_config: Optional[WebsockNotifConfig] = Field(default=None, alias="websockNotifConfig")
    reachability_type: Optional[ReachabilityType] = Field(default=None, alias="reachabilityType")
    location_type: Optional[LocationType] = Field(default=None, alias="locationType")
    accuracy: Optional[Accuracy] = Field(default=None)  
    ldr_type: Optional[LdrType] = Field(default=None, alias="ldrType")
    velocity_requested: Optional[VelocityRequested] = Field(default=None, alias="velocityRequested")
    loc_time_window: Optional[TimeWindow] = Field(default=None, alias="locTimeWindow")
    supported_gad_shapes: Optional[List[SupportedGADShapes]] = Field(default=None, alias="supportedGADShapes")
    association_type: Optional[AssociationType] = Field(default=None, alldrTypeias="associationType")
    ddd_stati: Optional[Annotated[List[DlDataDeliveryStatus], Field(min_length=1)]] = Field(default=None, alias="dddStati")
    snssai: Optional[Snssai] = Field(default=None)
    tgt_ns_threshold: Optional[SACInfo] = Field(default=None, alias="tgtNsThreshold")
    ns_rep_format: Optional[SACRepFormat] = Field(default=None, alias="nsRepFormat")
    uav_policy: Optional[UavPolicy] = Field(default=None, alias="uavPolicy")
    sub_type: Optional[SubType] = Field(default=None, alias="subType")
    req_ranging_sl_res: Optional[Annotated[List[RangingSlResult], Field(min_length=1)]] = Field(default=None, alias="reqRangingSlRes")
    loc_qo_s: Optional[LocationQoS] = Field(default=None, alias="locQoS")
    up_loc_rep_addr_af: Optional[UpLocRepAddrAfRm] = Field(default=None, alias="upLocRepAddrAf")
    location_area: Optional[LocationArea] = Field(default=None, alias="locationArea")
    location_area5_g: Optional[LocationArea5G] = Field(default=None, alias="locationArea5G")
    ddd_tra_descriptors: Optional[Annotated[List[DddTrafficDescriptor], Field(min_length=1)]] = Field(default=None, alias="dddTraDescriptors")
    monitoring_event_report: Optional[MonitoringEventReport] = Field(default=None, alias="monitoringEventReport")
    addn_mon_event_reports: Optional[List[MonitoringEventReport]] = Field(default=None, alias="addnMonEventReports")
    ue_ip_addr: Optional[IpAddr] = Field(default=None, alias="ueIpAddr")
    related_ues: Optional[Annotated[List[RelatedUE], Field(min_length=1)]] = Field(default=None, alias="relatedUEs")


  






